### ISSUE TITLE
ValueError: Layer model expects 1 input(s), but it received 2 input tensors.

### ISSUE THREAD

**Issue by GaoTiaoKang** [diogenes0319/FedMD_clean#2]

**Comment by zhanghui-svg** [comment]
Have you solved this problem？

**Comment by diogenes0319** [comment]
Hello,  sorry for the slow reply. 

Please see https://github.com/diogenes0319/FedMD_clean/issues/3 for the cause of the bug and the solution.  
I will close this issue as it is duplicated to issue #3.
